import { FeeDivision, ReservationDivision, ReservationStatus } from "./types";

export interface MunicipalityConfig {
  readonly key: string;
  readonly slug: string;
  readonly prefecture: string;
  readonly label: string;
  readonly reservationExcluded: boolean;
  readonly reservationStatus: Readonly<Record<string, string>>;
  readonly reservationDivision: Readonly<Record<string, string>>;
  readonly feeDivision: Readonly<Record<string, string>>;
}

export const MUNICIPALITIES = {
  MUNICIPALITY_KOUTOU: {
    key: "MUNICIPALITY_KOUTOU",
    slug: "koutou",
    prefecture: "tokyo",
    label: "江東区",
    reservationExcluded: false,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "予約あり",
      [ReservationStatus.STATUS_2]: "休館日",
      [ReservationStatus.STATUS_3]: "保守日",
      [ReservationStatus.STATUS_4]: "期間外",
      [ReservationStatus.STATUS_5]: "音出し予約",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.EVENING]: "夜間",
      [ReservationDivision.MORNING_ONE]: "①",
      [ReservationDivision.MORNING_TWO]: "②",
      [ReservationDivision.AFTERNOON_ONE]: "③",
      [ReservationDivision.AFTERNOON_TWO]: "④",
      [ReservationDivision.EVENING_ONE]: "⑤",
      [ReservationDivision.EVENING_TWO]: "⑥",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.DIVISION_1]: "①",
      [FeeDivision.DIVISION_2]: "②",
      [FeeDivision.DIVISION_3]: "③",
      [FeeDivision.DIVISION_4]: "④",
      [FeeDivision.DIVISION_5]: "⑤",
      [FeeDivision.DIVISION_6]: "⑥",
    },
  },
  MUNICIPALITY_BUNKYO: {
    key: "MUNICIPALITY_BUNKYO",
    slug: "bunkyo",
    prefecture: "tokyo",
    label: "文京区",
    reservationExcluded: true,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "一部空き",
      [ReservationStatus.STATUS_2]: "空きなし",
      [ReservationStatus.STATUS_3]: "抽選申込可能",
      [ReservationStatus.STATUS_4]: "申込期間外",
      [ReservationStatus.STATUS_5]: "公開対象外",
      [ReservationStatus.STATUS_6]: "休館",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.EVENING]: "夜間",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.DIVISION_1]: "１コマ",
      [FeeDivision.DIVISION_2]: "２コマ",
      [FeeDivision.DIVISION_3]: "３コマ",
      [FeeDivision.DIVISION_4]: "４コマ",
      [FeeDivision.DIVISION_5]: "５コマ",
    },
  },
  MUNICIPALITY_KITA: {
    key: "MUNICIPALITY_KITA",
    slug: "kita",
    prefecture: "tokyo",
    label: "北区",
    reservationExcluded: false,
    reservationStatus: {
      [ReservationStatus.VACANT]: "○",
      [ReservationStatus.STATUS_1]: "×",
      [ReservationStatus.STATUS_2]: "保守",
      [ReservationStatus.STATUS_3]: "休館",
      [ReservationStatus.STATUS_4]: "問い合わせ",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.EVENING]: "夜間",
      [ReservationDivision.DIVISION_1]: "①",
      [ReservationDivision.DIVISION_2]: "②",
      [ReservationDivision.DIVISION_3]: "③",
      [ReservationDivision.DIVISION_4]: "④",
      [ReservationDivision.DIVISION_5]: "⑤",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.ONE_HOUR]: "1時間",
      [FeeDivision.DIVISION_1]: "①",
      [FeeDivision.DIVISION_2]: "②",
      [FeeDivision.DIVISION_3]: "③",
      [FeeDivision.DIVISION_4]: "④",
      [FeeDivision.DIVISION_5]: "⑤",
    },
  },
  MUNICIPALITY_TOSHIMA: {
    key: "MUNICIPALITY_TOSHIMA",
    slug: "toshima",
    prefecture: "tokyo",
    label: "豊島区",
    reservationExcluded: true,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "一部空き",
      [ReservationStatus.STATUS_2]: "空きなし",
      [ReservationStatus.STATUS_3]: "申込期間外",
      [ReservationStatus.STATUS_4]: "休館",
      [ReservationStatus.STATUS_5]: "休館日",
      [ReservationStatus.STATUS_6]: "なし",
      [ReservationStatus.STATUS_7]: "公開対象外",
      [ReservationStatus.STATUS_8]: "抽選",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.EVENING]: "夜間",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.ONE_HOUR]: "1時間",
    },
  },
  MUNICIPALITY_EDOGAWA: {
    key: "MUNICIPALITY_EDOGAWA",
    slug: "edogawa",
    prefecture: "tokyo",
    label: "江戸川区",
    reservationExcluded: true,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "予約済",
      [ReservationStatus.STATUS_2]: "×",
      [ReservationStatus.STATUS_3]: "使用中止",
      [ReservationStatus.STATUS_4]: "休館日",
      [ReservationStatus.STATUS_5]: "工事",
      [ReservationStatus.STATUS_6]: "保守",
      [ReservationStatus.STATUS_7]: "清掃",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.AFTERNOON_ONE]: "午後1",
      [ReservationDivision.AFTERNOON_TWO]: "午後2",
      [ReservationDivision.EVENING]: "夜間",
      [ReservationDivision.EVENING_ONE]: "夜間1",
      [ReservationDivision.EVENING_TWO]: "夜間2",
      [ReservationDivision.DIVISION_1]: "0900-0930",
      [ReservationDivision.DIVISION_2]: "0930-1000",
      [ReservationDivision.DIVISION_3]: "1000-1030",
      [ReservationDivision.DIVISION_4]: "1030-1100",
      [ReservationDivision.DIVISION_5]: "1100-1130",
      [ReservationDivision.DIVISION_6]: "1130-1200",
      [ReservationDivision.DIVISION_7]: "1200-1230",
      [ReservationDivision.DIVISION_8]: "1230-1300",
      [ReservationDivision.DIVISION_9]: "1300-1330",
      [ReservationDivision.DIVISION_10]: "1330-1400",
      [ReservationDivision.DIVISION_11]: "1400-1430",
      [ReservationDivision.DIVISION_12]: "1430-1500",
      [ReservationDivision.DIVISION_13]: "1500-1530",
      [ReservationDivision.DIVISION_14]: "1530-1600",
      [ReservationDivision.DIVISION_15]: "1600-1630",
      [ReservationDivision.DIVISION_16]: "1630-1700",
      [ReservationDivision.DIVISION_17]: "1700-1730",
      [ReservationDivision.DIVISION_18]: "1730-1800",
      [ReservationDivision.DIVISION_19]: "1800-1830",
      [ReservationDivision.DIVISION_20]: "1830-1900",
      [ReservationDivision.DIVISION_21]: "1900-1930",
      [ReservationDivision.DIVISION_22]: "1930-2000",
      [ReservationDivision.DIVISION_23]: "2000-2030",
      [ReservationDivision.DIVISION_24]: "2030-2100",
      [ReservationDivision.DIVISION_25]: "2100-2130",
      [ReservationDivision.DIVISION_26]: "2130-2200",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.AFTERNOON_ONE]: "午後1",
      [FeeDivision.AFTERNOON_TWO]: "午後2",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.EVENING_ONE]: "夜間1",
      [FeeDivision.EVENING_TWO]: "夜間2",
      [FeeDivision.ONE_HOUR]: "1時間",
    },
  },
  MUNICIPALITY_ARAKAWA: {
    key: "MUNICIPALITY_ARAKAWA",
    slug: "arakawa",
    prefecture: "tokyo",
    label: "荒川区",
    reservationExcluded: false,
    reservationStatus: {
      [ReservationStatus.VACANT]: "○",
      [ReservationStatus.STATUS_1]: "×",
      [ReservationStatus.STATUS_2]: "保守",
      [ReservationStatus.STATUS_3]: "休館",
      [ReservationStatus.STATUS_4]: "開放",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.AFTERNOON_ONE]: "午後1",
      [ReservationDivision.AFTERNOON_TWO]: "午後2",
      [ReservationDivision.EVENING]: "夜間",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.AFTERNOON_ONE]: "午後1",
      [FeeDivision.AFTERNOON_TWO]: "午後2",
      [FeeDivision.EVENING]: "夜間",
    },
  },
  MUNICIPALITY_SUMIDA: {
    key: "MUNICIPALITY_SUMIDA",
    slug: "sumida",
    prefecture: "tokyo",
    label: "墨田区",
    reservationExcluded: false,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "一部空き",
      [ReservationStatus.STATUS_2]: "空きなし",
      [ReservationStatus.STATUS_3]: "申込期間外",
      [ReservationStatus.STATUS_4]: "休館",
      [ReservationStatus.STATUS_5]: "なし",
      [ReservationStatus.STATUS_6]: "公開対象外",
      [ReservationStatus.STATUS_7]: "抽選",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.EVENING]: "夜間",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.ONE_HOUR]: "1時間",
    },
  },
  MUNICIPALITY_OTA: {
    key: "MUNICIPALITY_OTA",
    slug: "ota",
    prefecture: "tokyo",
    label: "大田区",
    reservationExcluded: true,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "予約済",
      [ReservationStatus.STATUS_2]: "空枠なし",
      [ReservationStatus.STATUS_3]: "休館日",
      [ReservationStatus.STATUS_4]: "保守点検",
      [ReservationStatus.STATUS_5]: "施設整備",
      [ReservationStatus.STATUS_6]: "工事",
      [ReservationStatus.STATUS_7]: "×",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.AFTERNOON_ONE]: "午後1",
      [ReservationDivision.AFTERNOON_TWO]: "午後2",
      [ReservationDivision.EVENING]: "夜間",
      [ReservationDivision.EVENING_ONE]: "夜間1",
      [ReservationDivision.EVENING_TWO]: "夜間2",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.TWO_HOUR]: "1コマ",
    },
  },
  MUNICIPALITY_SUGINAMI: {
    key: "MUNICIPALITY_SUGINAMI",
    slug: "suginami",
    prefecture: "tokyo",
    label: "杉並区",
    reservationExcluded: true,
    reservationStatus: {
      [ReservationStatus.VACANT]: "予約可",
      [ReservationStatus.STATUS_1]: "予約不可",
      [ReservationStatus.STATUS_2]: "期間外",
      [ReservationStatus.STATUS_3]: "未確定/ホール未確定",
      [ReservationStatus.STATUS_4]: "休館",
      [ReservationStatus.STATUS_5]: "施設保守",
      [ReservationStatus.STATUS_6]: "その他",
      [ReservationStatus.STATUS_7]: "悪天候",
      [ReservationStatus.STATUS_8]: "工事",
      [ReservationStatus.STATUS_9]: "閉鎖",
      [ReservationStatus.STATUS_10]: "選挙",
      [ReservationStatus.STATUS_11]: "イベント",
      [ReservationStatus.STATUS_12]: "開放待ち",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.AFTERNOON_ONE]: "午後1",
      [ReservationDivision.AFTERNOON_TWO]: "午後2",
      [ReservationDivision.EVENING]: "夜間",
      [ReservationDivision.DIVISION_1]: "9時-",
      [ReservationDivision.DIVISION_2]: "10時-",
      [ReservationDivision.DIVISION_3]: "11時-",
      [ReservationDivision.DIVISION_4]: "12時-",
      [ReservationDivision.DIVISION_5]: "13時-",
      [ReservationDivision.DIVISION_6]: "14時-",
      [ReservationDivision.DIVISION_7]: "15時-",
      [ReservationDivision.DIVISION_8]: "16時-",
      [ReservationDivision.DIVISION_9]: "17時-",
      [ReservationDivision.DIVISION_10]: "18時-",
      [ReservationDivision.DIVISION_11]: "19時-",
      [ReservationDivision.DIVISION_12]: "20時-",
    },
    // NOTE: Uses ReservationDivision keys for AFTERNOON_ONE/TWO (existing behavior preserved)
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [ReservationDivision.AFTERNOON_ONE]: "午後1",
      [ReservationDivision.AFTERNOON_TWO]: "午後2",
      [FeeDivision.EVENING]: "夜間",
      [FeeDivision.ONE_HOUR]: "1時間",
    },
  },
  MUNICIPALITY_CHUO: {
    key: "MUNICIPALITY_CHUO",
    slug: "chuo",
    prefecture: "tokyo",
    label: "中央区",
    reservationExcluded: false,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "一部空き",
      [ReservationStatus.STATUS_2]: "空きなし",
      [ReservationStatus.STATUS_3]: "申込期間外",
      [ReservationStatus.STATUS_4]: "休館",
      [ReservationStatus.STATUS_5]: "なし",
      [ReservationStatus.STATUS_6]: "公開対象外",
      [ReservationStatus.STATUS_7]: "抽選",
      [ReservationStatus.STATUS_8]: "整備",
      [ReservationStatus.STATUS_9]: "抽選確認中",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.EVENING]: "夜間",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
    },
  },
  MUNICIPALITY_KAWASAKI: {
    key: "MUNICIPALITY_KAWASAKI",
    slug: "kawasaki",
    prefecture: "kanagawa",
    label: "川崎市",
    reservationExcluded: false,
    reservationStatus: {
      [ReservationStatus.VACANT]: "空き",
      [ReservationStatus.STATUS_1]: "予約あり",
      [ReservationStatus.STATUS_2]: "休館日",
      [ReservationStatus.STATUS_3]: "保守日・主催事業",
      [ReservationStatus.STATUS_4]: "一般開放",
      [ReservationStatus.STATUS_5]: "雨天",
      [ReservationStatus.STATUS_6]: "受付期間外",
      [ReservationStatus.STATUS_7]: "時間外",
      [ReservationStatus.STATUS_8]: "取消処理中",
      [ReservationStatus.STATUS_9]: "開放予定",
    },
    reservationDivision: {
      [ReservationDivision.MORNING]: "午前",
      [ReservationDivision.AFTERNOON]: "午後",
      [ReservationDivision.AFTERNOON_ONE]: "午後１",
      [ReservationDivision.AFTERNOON_TWO]: "午後２",
      [ReservationDivision.EVENING]: "夜間",
    },
    feeDivision: {
      [FeeDivision.MORNING]: "午前",
      [FeeDivision.AFTERNOON]: "午後",
      [FeeDivision.EVENING]: "夜間",
    },
  },
} as const satisfies Record<string, MunicipalityConfig>;

export type MunicipalityKey = keyof typeof MUNICIPALITIES;

export const MUNICIPALITY_KEYS = Object.keys(MUNICIPALITIES) as MunicipalityKey[];

export function getMunicipalityBySlug(slug: string): MunicipalityConfig | undefined {
  return Object.values(MUNICIPALITIES).find((m) => m.slug === slug);
}

export function getMunicipalityKeyBySlug(slug: string): MunicipalityKey | undefined {
  return MUNICIPALITY_KEYS.find((k) => MUNICIPALITIES[k].slug === slug);
}

export function getReservationTargets(): string[] {
  return Object.values(MUNICIPALITIES)
    .filter((m) => !m.reservationExcluded)
    .map((m) => `${m.prefecture}-${m.slug}`);
}

export function getAllMunicipalityTargets(): string[] {
  return Object.values(MUNICIPALITIES).map((m) => `${m.prefecture}-${m.slug}`);
}
