// Shared type definitions using `as const` objects.
// These replace TypeScript enums with zero-cost const objects that provide
// the same runtime behavior (e.g. ReservationStatus.VACANT) while also
// yielding string literal union types automatically.

export const ReservationStatus = {
  INVALID: "RESERVATION_STATUS_INVALID",
  VACANT: "RESERVATION_STATUS_VACANT",
  STATUS_1: "RESERVATION_STATUS_STATUS_1",
  STATUS_2: "RESERVATION_STATUS_STATUS_2",
  STATUS_3: "RESERVATION_STATUS_STATUS_3",
  STATUS_4: "RESERVATION_STATUS_STATUS_4",
  STATUS_5: "RESERVATION_STATUS_STATUS_5",
  STATUS_6: "RESERVATION_STATUS_STATUS_6",
  STATUS_7: "RESERVATION_STATUS_STATUS_7",
  STATUS_8: "RESERVATION_STATUS_STATUS_8",
  STATUS_9: "RESERVATION_STATUS_STATUS_9",
  STATUS_10: "RESERVATION_STATUS_STATUS_10",
  STATUS_11: "RESERVATION_STATUS_STATUS_11",
  STATUS_12: "RESERVATION_STATUS_STATUS_12",
  STATUS_13: "RESERVATION_STATUS_STATUS_13",
  STATUS_14: "RESERVATION_STATUS_STATUS_14",
  STATUS_15: "RESERVATION_STATUS_STATUS_15",
  STATUS_16: "RESERVATION_STATUS_STATUS_16",
  STATUS_17: "RESERVATION_STATUS_STATUS_17",
  STATUS_18: "RESERVATION_STATUS_STATUS_18",
  STATUS_19: "RESERVATION_STATUS_STATUS_19",
  STATUS_20: "RESERVATION_STATUS_STATUS_20",
} as const;
export type ReservationStatus = (typeof ReservationStatus)[keyof typeof ReservationStatus];

export const ReservationDivision = {
  INVALID: "RESERVATION_DIVISION_INVALID",
  MORNING: "RESERVATION_DIVISION_MORNING",
  MORNING_ONE: "RESERVATION_DIVISION_MORNING_ONE",
  MORNING_TWO: "RESERVATION_DIVISION_MORNING_TWO",
  AFTERNOON: "RESERVATION_DIVISION_AFTERNOON",
  AFTERNOON_ONE: "RESERVATION_DIVISION_AFTERNOON_ONE",
  AFTERNOON_TWO: "RESERVATION_DIVISION_AFTERNOON_TWO",
  EVENING: "RESERVATION_DIVISION_EVENING",
  EVENING_ONE: "RESERVATION_DIVISION_EVENING_ONE",
  EVENING_TWO: "RESERVATION_DIVISION_EVENING_TWO",
  DIVISION_1: "RESERVATION_DIVISION_DIVISION_1",
  DIVISION_2: "RESERVATION_DIVISION_DIVISION_2",
  DIVISION_3: "RESERVATION_DIVISION_DIVISION_3",
  DIVISION_4: "RESERVATION_DIVISION_DIVISION_4",
  DIVISION_5: "RESERVATION_DIVISION_DIVISION_5",
  DIVISION_6: "RESERVATION_DIVISION_DIVISION_6",
  DIVISION_7: "RESERVATION_DIVISION_DIVISION_7",
  DIVISION_8: "RESERVATION_DIVISION_DIVISION_8",
  DIVISION_9: "RESERVATION_DIVISION_DIVISION_9",
  DIVISION_10: "RESERVATION_DIVISION_DIVISION_10",
  DIVISION_11: "RESERVATION_DIVISION_DIVISION_11",
  DIVISION_12: "RESERVATION_DIVISION_DIVISION_12",
  DIVISION_13: "RESERVATION_DIVISION_DIVISION_13",
  DIVISION_14: "RESERVATION_DIVISION_DIVISION_14",
  DIVISION_15: "RESERVATION_DIVISION_DIVISION_15",
  DIVISION_16: "RESERVATION_DIVISION_DIVISION_16",
  DIVISION_17: "RESERVATION_DIVISION_DIVISION_17",
  DIVISION_18: "RESERVATION_DIVISION_DIVISION_18",
  DIVISION_19: "RESERVATION_DIVISION_DIVISION_19",
  DIVISION_20: "RESERVATION_DIVISION_DIVISION_20",
  DIVISION_21: "RESERVATION_DIVISION_DIVISION_21",
  DIVISION_22: "RESERVATION_DIVISION_DIVISION_22",
  DIVISION_23: "RESERVATION_DIVISION_DIVISION_23",
  DIVISION_24: "RESERVATION_DIVISION_DIVISION_24",
  DIVISION_25: "RESERVATION_DIVISION_DIVISION_25",
  DIVISION_26: "RESERVATION_DIVISION_DIVISION_26",
  DIVISION_27: "RESERVATION_DIVISION_DIVISION_27",
  DIVISION_28: "RESERVATION_DIVISION_DIVISION_28",
  DIVISION_29: "RESERVATION_DIVISION_DIVISION_29",
  DIVISION_30: "RESERVATION_DIVISION_DIVISION_30",
} as const;
export type ReservationDivision = (typeof ReservationDivision)[keyof typeof ReservationDivision];

export const FeeDivision = {
  INVALID: "FEE_DIVISION_INVALID",
  MORNING: "FEE_DIVISION_MORNING",
  MORNING_ONE: "FEE_DIVISION_MORNING_ONE",
  MORNING_TWO: "FEE_DIVISION_MORNING_TWO",
  AFTERNOON: "FEE_DIVISION_AFTERNOON",
  AFTERNOON_ONE: "FEE_DIVISION_AFTERNOON_ONE",
  AFTERNOON_TWO: "FEE_DIVISION_AFTERNOON_TWO",
  EVENING: "FEE_DIVISION_EVENING",
  EVENING_ONE: "FEE_DIVISION_EVENING_ONE",
  EVENING_TWO: "FEE_DIVISION_EVENING_TWO",
  ONE_HOUR: "FEE_DIVISION_ONE_HOUR",
  TWO_HOUR: "FEE_DIVISION_TWO_HOUR",
  DIVISION_1: "FEE_DIVISION_DIVISION_1",
  DIVISION_2: "FEE_DIVISION_DIVISION_2",
  DIVISION_3: "FEE_DIVISION_DIVISION_3",
  DIVISION_4: "FEE_DIVISION_DIVISION_4",
  DIVISION_5: "FEE_DIVISION_DIVISION_5",
  DIVISION_6: "FEE_DIVISION_DIVISION_6",
  DIVISION_7: "FEE_DIVISION_DIVISION_7",
  DIVISION_8: "FEE_DIVISION_DIVISION_8",
  DIVISION_9: "FEE_DIVISION_DIVISION_9",
  DIVISION_10: "FEE_DIVISION_DIVISION_10",
} as const;
export type FeeDivision = (typeof FeeDivision)[keyof typeof FeeDivision];

export const AvailabilityDivision = {
  INVALID: "AVAILABILITY_DIVISION_INVALID",
  AVAILABLE: "AVAILABILITY_DIVISION_AVAILABLE",
  UNAVAILABLE: "AVAILABILITY_DIVISION_UNAVAILABLE",
  UNKNOWN: "AVAILABILITY_DIVISION_UNKNOWN",
} as const;
export type AvailabilityDivision = (typeof AvailabilityDivision)[keyof typeof AvailabilityDivision];

export const EquipmentDivision = {
  INVALID: "EQUIPMENT_DIVISION_INVALID",
  EQUIPPED: "EQUIPMENT_DIVISION_EQUIPPED",
  UNEQUIPPED: "EQUIPMENT_DIVISION_UNEQUIPPED",
  UNKNOWN: "EQUIPMENT_DIVISION_UNKNOWN",
} as const;
export type EquipmentDivision = (typeof EquipmentDivision)[keyof typeof EquipmentDivision];

export const InstitutionSize = {
  INVALID: "INSTITUTION_SIZE_INVALID",
  LARGE: "INSTITUTION_SIZE_LARGE",
  MEDIUM: "INSTITUTION_SIZE_MEDIUM",
  SMALL: "INSTITUTION_SIZE_SMALL",
  UNKNOWN: "INSTITUTION_SIZE_UNKNOWN",
} as const;
export type InstitutionSize = (typeof InstitutionSize)[keyof typeof InstitutionSize];

export type UsageFeeEntry = {
  division: string;
  fee: number;
};

export type Institution = {
  id: string;
  prefecture: string;
  municipality: string;
  building: string;
  institution: string;
  building_kana: string;
  institution_kana: string;
  building_system_name: string;
  institution_system_name: string;
  capacity?: number | null;
  area?: number | null;
  institution_size: string;
  fee_divisions: string[];
  weekday_usage_fee: UsageFeeEntry[];
  holiday_usage_fee: UsageFeeEntry[];
  address: string;
  is_available_strings: string;
  is_available_woodwind: string;
  is_available_brass: string;
  is_available_percussion: string;
  is_equipped_music_stand: string;
  is_equipped_piano: string;
  website_url: string;
  layout_image_url: string;
  lottery_period: string;
  note: string;
};

// Scraper-compatible type aliases
export type Division = ReservationDivision;
export type Status = ReservationStatus;

export type Reservation = { [K in Division]?: Status };

export type TransformOutput = {
  room_name: string;
  date: string;
  reservation: Reservation;
}[];
