env:
  browser: true
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  "react/display-name": "off"
  "react/prop-types": "off"
  "react/react-in-jsx-scope": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
