override: true
schema:
  - ${GRAPHQL_ENDPOINT}:
      headers:
        x-hasura-admin-secret: ${ADMIN_SECRET}
        x-hasura-role: user
documents:
  - ./packages/front/api/queries/*.graphql
generates:
  ./packages/front/api/graphql-client.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
