override: true
schema:
  - https://shisetsu-graphql.herokuapp.com/v1/graphql:
      headers:
        x-hasura-admin-secret: ${ADMIN_SECRET}
documents:
  - ./src/api/queries/*.graphql
generates:
  ./src/api/graphql-client.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withComponent: false
      withHooks: true
      withHOC: false