/* eslint-disable */
import * as types from "./graphql";
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "query institutionDetail($id: uuid!) {\n  institutions_connection(where: {id: {_eq: $id}}, first: 1) {\n    edges {\n      node {\n        id\n        prefecture\n        municipality\n        building\n        institution\n        capacity\n        area\n        fee_divisions\n        weekday_usage_fee\n        holiday_usage_fee\n        address\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        website_url\n        layout_image_url\n        lottery_period\n        note\n      }\n    }\n  }\n}": typeof types.InstitutionDetailDocument;
  "query institutionReservations($id: uuid!, $startDate: date, $endDate: date) {\n  reservations_connection(\n    where: {institution_id: {_eq: $id}, date: {_gte: $startDate, _lte: $endDate}}\n    order_by: {date: asc}\n    first: 1000\n  ) {\n    edges {\n      node {\n        id\n        date\n        reservation\n        updated_at\n      }\n    }\n  }\n}": typeof types.InstitutionReservationsDocument;
  "query institutions($first: Int, $after: String, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null) {\n  institutions_connection(\n    first: $first\n    after: $after\n    where: {municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}\n    order_by: {municipality: asc, building_kana: asc, institution_kana: asc}\n  ) {\n    edges {\n      node {\n        id\n        municipality\n        building\n        institution\n        institution_size\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        updated_at\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}": typeof types.InstitutionsDocument;
  "query reservations($first: Int, $after: String, $prefecture: prefecture = null, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null, $startDate: date, $endDate: date, $isHoliday: Boolean, $isMorningVacant: Boolean, $isAfternoonVacant: Boolean, $isEveningVacant: Boolean) {\n  searchable_reservations_connection(\n    first: $first\n    after: $after\n    where: {_and: {institution: {prefecture: {_eq: $prefecture}, municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}, date: {_gte: $startDate, _lte: $endDate}, is_morning_vacant: {_eq: $isMorningVacant}, is_afternoon_vacant: {_eq: $isAfternoonVacant}, is_evening_vacant: {_eq: $isEveningVacant}, is_holiday: {_eq: $isHoliday}}}\n    order_by: {date: asc}\n  ) {\n    edges {\n      node {\n        id\n        reservation {\n          id\n          date\n          reservation\n          updated_at\n        }\n        institution {\n          id\n          municipality\n          building\n          institution\n          institution_size\n        }\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}": typeof types.ReservationsDocument;
};
const documents: Documents = {
  "query institutionDetail($id: uuid!) {\n  institutions_connection(where: {id: {_eq: $id}}, first: 1) {\n    edges {\n      node {\n        id\n        prefecture\n        municipality\n        building\n        institution\n        capacity\n        area\n        fee_divisions\n        weekday_usage_fee\n        holiday_usage_fee\n        address\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        website_url\n        layout_image_url\n        lottery_period\n        note\n      }\n    }\n  }\n}":
    types.InstitutionDetailDocument,
  "query institutionReservations($id: uuid!, $startDate: date, $endDate: date) {\n  reservations_connection(\n    where: {institution_id: {_eq: $id}, date: {_gte: $startDate, _lte: $endDate}}\n    order_by: {date: asc}\n    first: 1000\n  ) {\n    edges {\n      node {\n        id\n        date\n        reservation\n        updated_at\n      }\n    }\n  }\n}":
    types.InstitutionReservationsDocument,
  "query institutions($first: Int, $after: String, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null) {\n  institutions_connection(\n    first: $first\n    after: $after\n    where: {municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}\n    order_by: {municipality: asc, building_kana: asc, institution_kana: asc}\n  ) {\n    edges {\n      node {\n        id\n        municipality\n        building\n        institution\n        institution_size\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        updated_at\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}":
    types.InstitutionsDocument,
  "query reservations($first: Int, $after: String, $prefecture: prefecture = null, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null, $startDate: date, $endDate: date, $isHoliday: Boolean, $isMorningVacant: Boolean, $isAfternoonVacant: Boolean, $isEveningVacant: Boolean) {\n  searchable_reservations_connection(\n    first: $first\n    after: $after\n    where: {_and: {institution: {prefecture: {_eq: $prefecture}, municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}, date: {_gte: $startDate, _lte: $endDate}, is_morning_vacant: {_eq: $isMorningVacant}, is_afternoon_vacant: {_eq: $isAfternoonVacant}, is_evening_vacant: {_eq: $isEveningVacant}, is_holiday: {_eq: $isHoliday}}}\n    order_by: {date: asc}\n  ) {\n    edges {\n      node {\n        id\n        reservation {\n          id\n          date\n          reservation\n          updated_at\n        }\n        institution {\n          id\n          municipality\n          building\n          institution\n          institution_size\n        }\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}":
    types.ReservationsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query institutionDetail($id: uuid!) {\n  institutions_connection(where: {id: {_eq: $id}}, first: 1) {\n    edges {\n      node {\n        id\n        prefecture\n        municipality\n        building\n        institution\n        capacity\n        area\n        fee_divisions\n        weekday_usage_fee\n        holiday_usage_fee\n        address\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        website_url\n        layout_image_url\n        lottery_period\n        note\n      }\n    }\n  }\n}"
): (typeof documents)["query institutionDetail($id: uuid!) {\n  institutions_connection(where: {id: {_eq: $id}}, first: 1) {\n    edges {\n      node {\n        id\n        prefecture\n        municipality\n        building\n        institution\n        capacity\n        area\n        fee_divisions\n        weekday_usage_fee\n        holiday_usage_fee\n        address\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        website_url\n        layout_image_url\n        lottery_period\n        note\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query institutionReservations($id: uuid!, $startDate: date, $endDate: date) {\n  reservations_connection(\n    where: {institution_id: {_eq: $id}, date: {_gte: $startDate, _lte: $endDate}}\n    order_by: {date: asc}\n    first: 1000\n  ) {\n    edges {\n      node {\n        id\n        date\n        reservation\n        updated_at\n      }\n    }\n  }\n}"
): (typeof documents)["query institutionReservations($id: uuid!, $startDate: date, $endDate: date) {\n  reservations_connection(\n    where: {institution_id: {_eq: $id}, date: {_gte: $startDate, _lte: $endDate}}\n    order_by: {date: asc}\n    first: 1000\n  ) {\n    edges {\n      node {\n        id\n        date\n        reservation\n        updated_at\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query institutions($first: Int, $after: String, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null) {\n  institutions_connection(\n    first: $first\n    after: $after\n    where: {municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}\n    order_by: {municipality: asc, building_kana: asc, institution_kana: asc}\n  ) {\n    edges {\n      node {\n        id\n        municipality\n        building\n        institution\n        institution_size\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        updated_at\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}"
): (typeof documents)["query institutions($first: Int, $after: String, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null) {\n  institutions_connection(\n    first: $first\n    after: $after\n    where: {municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}\n    order_by: {municipality: asc, building_kana: asc, institution_kana: asc}\n  ) {\n    edges {\n      node {\n        id\n        municipality\n        building\n        institution\n        institution_size\n        is_available_strings\n        is_available_woodwind\n        is_available_brass\n        is_available_percussion\n        is_equipped_music_stand\n        is_equipped_piano\n        updated_at\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query reservations($first: Int, $after: String, $prefecture: prefecture = null, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null, $startDate: date, $endDate: date, $isHoliday: Boolean, $isMorningVacant: Boolean, $isAfternoonVacant: Boolean, $isEveningVacant: Boolean) {\n  searchable_reservations_connection(\n    first: $first\n    after: $after\n    where: {_and: {institution: {prefecture: {_eq: $prefecture}, municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}, date: {_gte: $startDate, _lte: $endDate}, is_morning_vacant: {_eq: $isMorningVacant}, is_afternoon_vacant: {_eq: $isAfternoonVacant}, is_evening_vacant: {_eq: $isEveningVacant}, is_holiday: {_eq: $isHoliday}}}\n    order_by: {date: asc}\n  ) {\n    edges {\n      node {\n        id\n        reservation {\n          id\n          date\n          reservation\n          updated_at\n        }\n        institution {\n          id\n          municipality\n          building\n          institution\n          institution_size\n        }\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}"
): (typeof documents)["query reservations($first: Int, $after: String, $prefecture: prefecture = null, $municipality: [String!], $isAvailableStrings: availavility_division = null, $isAvailableWoodwind: availavility_division = null, $isAvailableBrass: availavility_division = null, $isAvailablePercussion: availavility_division = null, $institutionSizes: [String!] = null, $startDate: date, $endDate: date, $isHoliday: Boolean, $isMorningVacant: Boolean, $isAfternoonVacant: Boolean, $isEveningVacant: Boolean) {\n  searchable_reservations_connection(\n    first: $first\n    after: $after\n    where: {_and: {institution: {prefecture: {_eq: $prefecture}, municipality: {_in: $municipality}, is_available_strings: {_eq: $isAvailableStrings}, is_available_woodwind: {_eq: $isAvailableWoodwind}, is_available_brass: {_eq: $isAvailableBrass}, is_available_percussion: {_eq: $isAvailablePercussion}, institution_size: {_in: $institutionSizes}}, date: {_gte: $startDate, _lte: $endDate}, is_morning_vacant: {_eq: $isMorningVacant}, is_afternoon_vacant: {_eq: $isAfternoonVacant}, is_evening_vacant: {_eq: $isEveningVacant}, is_holiday: {_eq: $isHoliday}}}\n    order_by: {date: asc}\n  ) {\n    edges {\n      node {\n        id\n        reservation {\n          id\n          date\n          reservation\n          updated_at\n        }\n        institution {\n          id\n          municipality\n          building\n          institution\n          institution_size\n        }\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
