name: "Scraper Action"
description: "Run Playwright scraper tests and save results"

inputs:
  municipality:
    description: "Municipality to scrape"
    required: false
    default: ""
  shardIndex:
    description: "Shard index"
    required: true
  shardTotal:
    description: "Total number of shards"
    required: true
  nodeModulesCacheKey:
    description: "Cache key for node_modules"
    required: true
  playwrightCacheKey:
    description: "Cache key for Playwright browsers"
    required: true
  debug:
    description: "Enable debug mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: "npm"
        cache-dependency-path: "**/package-lock.json"
        node-version: "24"
    - name: Restore cached node_modules
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: "**/node_modules"
        key: ${{ inputs.nodeModulesCacheKey }}
    - name: Restore Playwright browsers
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ inputs.playwrightCacheKey }}
    - name: Run Playwright tests
      shell: bash
      working-directory: packages/scraper
      run: |
        if [ "${{ inputs.debug }}" == "true" ]; then
          DEBUG=pw:api npx playwright test ${{ inputs.municipality }} --shard=${{ inputs.shardIndex }}/${{ inputs.shardTotal }}
        else
          npx playwright test ${{ inputs.municipality }} --shard=${{ inputs.shardIndex }}/${{ inputs.shardTotal }}
        fi
    - name: Check test results
      id: check-results
      shell: bash
      working-directory: packages/scraper
      run: |
        if [ -d "test-results" ]; then
          echo "test-results-exist=true" >> $GITHUB_OUTPUT
          ls -R test-results
        else
          echo "test-results-exist=false" >> $GITHUB_OUTPUT
          echo "No test results found"
        fi
    - name: Save scraped data
      if: ${{ steps.check-results.outputs.test-results-exist == 'true' }}
      shell: bash
      working-directory: packages/scraper
      env:
        GRAPHQL_ENDPOINT: ${{ env.GRAPHQL_ENDPOINT }}
        M2M_TOKEN: ${{ env.M2M_TOKEN }}
      run: |
        node tools/updateReservations.ts ${{ inputs.municipality }}
