name: reg-suit

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth:  0
      - name: Set Node.js
        uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-npm
      - name: npm install
        run: npm install
      - name: workaround for detached HEAD
        run: |
           git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: run storycap
        run: npm run storycap
      - name: run reg-suit
        run: npm run reg-suit

env:
  REG_NOTICE_CLIENT_ID: ${{ secrets.REG_NOTICE_CLIENT_ID }}